### ISSUE TITLE
Logout is not protected

### ISSUE THREAD

**Issue by Casperhr** [anthonycastelli/Vapor-JWTAuthorization#1]
Shouldn't logout route be protected?

since you expect user to be in request
```
   var user = try request.user()
        user.token = nil
        try user.save()
```

**Comment by anthonycastelli** [comment]
There really isn't a need anymore for a logout method since it's not a good idea to store the JWT token in the database. Have a look at the revised code.

**Comment by rgkobashi** [comment]
@anthonycastelli where can I look the revised code?
