### ISSUE TITLE
Tokens are valid for 5 min from server start time

### ISSUE THREAD

**Issue by franciscojrp** [anthonycastelli/Vapor-JWTAuthorization#2]
As what you pass to the expiration claim is only calculated once:

static let AccesTokenValidationLength = Date() + (60 * 5) // 5 Minutes later

after 5 minutes all fresh tokens are already outdated

**Comment by anthonycastelli** [comment]
Good catch! I always forget about this repository so sorry it has taken me a while to get this upgraded.
